[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#7c6f64"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#bdae93"
yellow = "#fabd2f"

[colors.normal]
black = "#665c54"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#ef342d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
background = "#1d2021"
foreground = "#ebdbb2"

[font]
size = 12

[font.normal]
family = "JetBrainsMonoNL Nerd Font"

[font.offset]
x = -1
y = -2

[scrolling]
history = 10000
multiplier = 3

[shell]
program = "/usr/bin/zsh"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 0
y = 0

[window.dimensions]
columns = 120
lines = 30
