source = ~/.config/omarchy/current/theme/hyprlock.conf

background {
    monitor =
    color = $color
    path = ~/.config/omarchy/current/background
    blur_passes = 4
}

auth {
    fingerprint:enabled = false
}

animations {
    enabled = true
}

# Password field
input-field {
    monitor =
    size = 720, 100
    position = 0, -640
    halign = center
    valign = center

    inner_color = rgba(50, 48, 47, 0.48)
    outer_color = rgba(235, 219, 178, 0.48)
    outline_thickness = 4

    font_family = JetBrainsMonoNL Nerd Font Mono
    font_color = rgba(235, 219, 178, 1)

    placeholder_text = Enter password…
    check_color = rgba(250, 189, 47, 0.72)
    fail_text = <i>$PAMFAIL</i>
    fail_color = rgba(251, 73, 52, 0.72)

    rounding = 64
    shadow_passes = 0
    fade_on_empty = false

    dots_size = 0.22
    dots_spacing = 0.36
    dots_center = true
}

# Lock icon
label {
    monitor =
    text = 󰌾
    color = rgba(235, 219, 178, 0.72)
    font_size = 24
    font_family = JetBrainsMonoNL Nerd Font Mono
    position = -300, -640
    halign = center
    valign = center
}

# User field
shape {
    monitor =
    halign = center
    valign = center
    border_size = 4
    border_color = rgba(235, 219, 178, 0.08)
    rounding = 64
    color = rgba(50, 48, 47, 0.16)
    position = 0, -516
    size = 720, 100
}

# User icon
label {
    monitor =
    text = 
    color = rgba(235, 219, 178, 0.4)
    font_size = 24
    font_family = JetBrainsMonoNL Nerd Font Mono
    position = -300, -516
    halign = center
    valign = center
}

# Logged in user
label {
    monitor =
    text = $USER
    color = rgba(235, 219, 178, 0.48)
    font_size = 26
    font_family = JetBrainsMonoNL Nerd Font Mono
    position = 0, -516
    halign = center
    valign = center
}

# Date display
label {
    monitor =
    text = cmd[update:1000] echo -e "$(LC_TIME=en_US.UTF-8 date +"%A, %d %B %Y")"
    color = rgba(235, 219, 178, 0.32)
    font_size = 32
    font_family = JetBrainsMonoNL Nerd Font Mono
    position = 0, 640
    halign = center
    valign = center
}

# Time display
label {
    monitor =
    text = cmd[update:1000] echo -e "$(LC_TIME=en_US.UTF-8 date +"%H:%M")"
    color = rgba(235, 219, 178, 0.64)
    font_size = 288
    font_family = QuinqueFive
    position = 0, 400
    halign = center
    valign = center
}

# Failed attempts
label {
    monitor =
    text = cmd[update:1000] if (( $ATTEMPTS > 1 )); then echo "You already tried $ATTEMPTS times…"; else echo ""; fi
    color = rgba(235, 219, 178, 0.32)
    font_size = 16
    font_family = JetBrainsMonoNL Nerd Font Mono
    position = 0, -720
    halign = center
    valign = center
}

# Hint text
label {
    monitor =
    text = cmd[update:1000] if (( $ATTEMPTS > 3 )); then echo "A hint of your password"; else echo ""; fi
    color = rgba(235, 219, 178, 0.32)
    font_size = 16
    font_family = JetBrainsMonoNL Nerd Font Mono
    position = 0, -748
    halign = center
    valign = center
}

