[colors]
[colors.primary]
background = "0x1d2021"
foreground = "0xebdbb2"

[colors.normal]
black = "0x595959"
red = "0xea6962"
green = "0xa9b665"
yellow = "0xd8a657"
blue = "0x7daea3"
magenta = "0xd3869b"
cyan = "0x89b482"
white = "0xebdbb2"

[colors.bright]
black = "0x595959"
red = "0xea6962"
green = "0xa9b665"
yellow = "0xd8a657"
blue = "0x7daea3"
magenta = "0xd3869b"
cyan = "0x89b482"
white = "0xebdbb2"
