# Background and foreground colors
background = #f5e4d8
foreground = #3a1911

# Standard colors
palette = 0=#f5e4d8
palette = 1=#562b00
palette = 2=#653e00
palette = 3=#7b5521
palette = 4=#805f36
palette = 5=#563819
palette = 6=#875c26
palette = 7=#3a1911

# Bright colors
palette = 8=#7f7974
palette = 9=#7c4b14
palette = 10=#8b5f0f
palette = 11=#a27832
palette = 12=#a7824b
palette = 13=#7b582f
palette = 14=#af7f36
palette = 15=#5e362b
