$color = rgba(245, 228, 216, 1)
$inner_color = rgba(245, 228, 216, 0.66)
$outer_color = rgba(86, 56, 25, 1)
$font_color = rgba(58, 25, 17, 1)
$placeholder_color = rgba(58, 25, 17, 0.7)
$check_color = rgba(135, 92, 38, 1)
