return {
  -- {
  --   'saghen/blink.cmp',
  --   dependencies = { 'rafamadriz/friendly-snippets' },
  --   version = '1.*',
  --
  --   opts = {
  --     -- 'default' (recommended) for mappings similar to built-in completions (C-y to accept)
  --     -- 'super-tab' for mappings similar to vscode (tab to accept)
  --     -- 'enter' for enter to accept
  --     -- 'none' for no mappings
  --     --
  --     -- All presets have the following mappings:
  --     -- C-space: Open menu or open docs if already open
  --     -- C-n/C-p or Up/Down: Select next/previous item
  --     -- C-e: Hide menu
  --     -- C-k: Toggle signature help (if signature.enabled = true)
  --     --
  --     -- See :h blink-cmp-config-keymap for defining your own keymap
  --     keymap = { preset = 'enter' },
  --
  --     appearance = {
  --       use_nvim_cmp_as_default = false,
  --       nerd_font_variant = 'mono'
  --     },
  --     completion = {
  --       documentation = { auto_show = true },
  --       list = { selection = { preselect = false, auto_insert = true } },
  --       menu = {
  --         -- nvim-cmp style menu
  --         draw = {
  --           treesitter = { "lsp" },
  --           columns = {
  --             { "label",     "label_description", gap = 1 },
  --             { "kind_icon", "kind" }
  --           },
  --         }
  --       },
  --     },
  --
  --     sources = {
  --       default = { 'lsp', 'buffer', 'snippets', 'path' },
  --     },
  --     fuzzy = { implementation = "prefer_rust_with_warning" }
  --   },
  --   opts_extend = { "sources.default" }
  -- }
}
